/*
 * generated by Xtext 2.10.0
 */
package org.softlang.metalib.xtext.fsml.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.softlang.metalib.xtext.fsml.ui.internal.FsmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FsmlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FsmlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FsmlActivator.getInstance().getInjector(FsmlActivator.ORG_SOFTLANG_METALIB_XTEXT_FSML_FSML);
	}
	
}
