/**
 * generated by Xtext 2.10.0
 */
package org.softlang.metalib.xtext.fsml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.softlang.metalib.xtext.fsml.ui.AbstractFsmlUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class FsmlUiModule extends AbstractFsmlUiModule {
  public FsmlUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
