/*
 * generated by Xtext 2.10.0
 */
package org.softlang.metalib.xtext.fsml


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class FsmlRuntimeModule extends AbstractFsmlRuntimeModule {

}
