/**
 * generated by Xtext 2.10.0
 */
package org.softlang.metalib.xtext.fsml.scoping;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.softlang.metalib.xtext.fsml.fsml.FSM;
import org.softlang.metalib.xtext.fsml.fsml.FSMState;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class FsmlScopeProvider extends AbstractDeclarativeScopeProvider {
  public IScope scope_FSMTransition_target(final FSM fsm, final EReference ref) {
    EList<FSMState> _states = fsm.getStates();
    return Scopes.scopeFor(_states);
  }
}
