/*
 * generated by Xtext 2.10.0
 */
package org.softlang.metalib.xtext.fsml.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFsmlScopeProvider extends DelegatingScopeProvider {
}
