/**
 * generated by Xtext 2.10.0
 */
package org.softlang.metalib.xtext.fsml;

import org.softlang.metalib.xtext.fsml.AbstractFsmlRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class FsmlRuntimeModule extends AbstractFsmlRuntimeModule {
}
