/**
 * generated by Xtext 2.10.0
 */
package org.softlang.metalib.xtext.fsml;

import org.softlang.metalib.xtext.fsml.FsmlStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class FsmlStandaloneSetup extends FsmlStandaloneSetupGenerated {
  public static void doSetup() {
    FsmlStandaloneSetup _fsmlStandaloneSetup = new FsmlStandaloneSetup();
    _fsmlStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
