/*
 * generated by Xtext 2.10.0
 */
package org.softlang.metalib.xtext.fsml.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class FsmlUiModule extends AbstractFsmlUiModule {
}
