/*
 * generated by Xtext 2.10.0
 */
package org.softlang.metalib.xtext.fsml.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FsmlAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/softlang/metalib/xtext/fsml/parser/antlr/internal/InternalFsml.tokens");
	}
}
