/**
 * generated by Xtext 2.10.0
 */
package org.softlang.metalib.xtext.fsml.fsml;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FSM</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.softlang.metalib.xtext.fsml.fsml.FSM#getStates <em>States</em>}</li>
 * </ul>
 *
 * @see org.softlang.metalib.xtext.fsml.fsml.FsmlPackage#getFSM()
 * @model
 * @generated
 */
public interface FSM extends EObject
{
  /**
   * Returns the value of the '<em><b>States</b></em>' containment reference list.
   * The list contents are of type {@link org.softlang.metalib.xtext.fsml.fsml.FSMState}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>States</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>States</em>' containment reference list.
   * @see org.softlang.metalib.xtext.fsml.fsml.FsmlPackage#getFSM_States()
   * @model containment="true"
   * @generated
   */
  EList<FSMState> getStates();

} // FSM
