/**
 * generated by Xtext 2.10.0
 */
package org.softlang.metalib.xtext.fsml.fsml;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.softlang.metalib.xtext.fsml.fsml.FsmlPackage
 * @generated
 */
public interface FsmlFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FsmlFactory eINSTANCE = org.softlang.metalib.xtext.fsml.fsml.impl.FsmlFactoryImpl.init();

  /**
   * Returns a new object of class '<em>FSM</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FSM</em>'.
   * @generated
   */
  FSM createFSM();

  /**
   * Returns a new object of class '<em>FSM State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FSM State</em>'.
   * @generated
   */
  FSMState createFSMState();

  /**
   * Returns a new object of class '<em>FSM Transition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FSM Transition</em>'.
   * @generated
   */
  FSMTransition createFSMTransition();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  FsmlPackage getFsmlPackage();

} //FsmlFactory
